export const ACCIONES_AUDITORIA = {
  // Usuarios
  CREAR_USUARIO: 'CREAR_USUARIO',
  ACTUALIZAR_USUARIO: 'ACTUALIZAR_USUARIO',
  ELIMINAR_USUARIO: 'ELIMINAR_USUARIO',
  CAMBIAR_CONTRASENA_PROPIA: 'CAMBIAR_CONTRASENA_PROPIA',
  // Sectores
  CREAR_SECTOR: 'CREAR_SECTOR',
  ACTUALIZAR_SECTOR: 'ACTUALIZAR_SECTOR',
  ELIMINAR_SECTOR: 'ELIMINAR_SECTOR',
  // Proveedores
  CREAR_PROVEEDOR: 'CREAR_PROVEEDOR',
  ACTUALIZAR_PROVEEDOR: 'ACTUALIZAR_PROVEEDOR',
  ELIMINAR_PROVEEDOR: 'ELIMINAR_PROVEEDOR',
  // Clientes
  CREAR_CLIENTE: 'CREAR_CLIENTE',
  ACTUALIZAR_CLIENTE: 'ACTUALIZAR_CLIENTE',
  ELIMINAR_CLIENTE: 'ELIMINAR_CLIENTE',
  // Proyectos
  CREAR_PROYECTO: 'CREAR_PROYECTO',
  ACTUALIZAR_PROYECTO: 'ACTUALIZAR_PROYECTO',
  ELIMINAR_PROYECTO: 'ELIMINAR_PROYECTO',
  RECALCULAR_COSTO_SEG_PROYECTO: 'RECALCULAR_COSTO_SEG_PROYECTO',
  // Tareas
  CREAR_TAREA: 'CREAR_TAREA',
  ACTUALIZAR_TAREA: 'ACTUALIZAR_TAREA',
  ELIMINAR_TAREA: 'ELIMINAR_TAREA',
  // Cotizaciones
  CREAR_COTIZACION: 'CREAR_COTIZACION',
  // Propuestas de inversión
  CREAR_PROPUESTA_INVERSION: 'CREAR_PROPUESTA_INVERSION',
  // Órdenes de compra
  CREAR_ORDEN_COMPRA: 'CREAR_ORDEN_COMPRA',
  ACTUALIZAR_ORDEN_COMPRA: 'ACTUALIZAR_ORDEN_COMPRA',
  ELIMINAR_ORDEN_COMPRA: 'ELIMINAR_ORDEN_COMPRA',
  ADJUNTAR_FACTURA_ORDEN_COMPRA: 'ADJUNTAR_FACTURA_ORDEN_COMPRA',
  // Transiciones de estado de OC
  ENVIAR_ORDEN_COMPRA: 'ENVIAR_ORDEN_COMPRA',
  APROBAR_ORDEN_COMPRA: 'APROBAR_ORDEN_COMPRA',
  RECHAZAR_ORDEN_COMPRA: 'RECHAZAR_ORDEN_COMPRA',
  MARCAR_EN_CONSULTA_ORDEN_COMPRA: 'MARCAR_EN_CONSULTA_ORDEN_COMPRA',
  RESPONDER_CONSULTA_ORDEN_COMPRA: 'RESPONDER_CONSULTA_ORDEN_COMPRA',
  OBSERVAR_PAGO_ORDEN_COMPRA: 'OBSERVAR_PAGO_ORDEN_COMPRA',
  RESOLVER_OBSERVACION_ORDEN_COMPRA: 'RESOLVER_OBSERVACION_ORDEN_COMPRA',
  CONFIRMAR_PAGO_ORDEN_COMPRA: 'CONFIRMAR_PAGO_ORDEN_COMPRA',
  ANULAR_ORDEN_COMPRA: 'ANULAR_ORDEN_COMPRA',
  // Comentarios
  CREAR_COMENTARIO: 'CREAR_COMENTARIO',
  // Tipos de cambio
  ACTUALIZAR_TIPO_CAMBIO: 'ACTUALIZAR_TIPO_CAMBIO',
} as const;
